server:
  port: 8888
spring:
  profiles:
#  外置JDBC，redis和Mail配置文件
    active: redis,jdbc,mail
#  关闭thymeleaf页面缓存
  thymeleaf:
    cache: false
#  配置国际化资源文件
  messages:
    basename: i18n.login
#  MyBatis配置
mybatis:
  configuration:
#  配置mybatis的配置文件路径
    mapper-locations: classpath:mapper/*.xml
#  配置xml映射文件中指定的实体类别名路径
    type-aliases-package: com.itxin.model.domain
    #   开启驼峰命名匹配规则
    map-underscore-to-camel-case: true
#  Pagehelper分页配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
#  浏览器Cookie相关设置
COOKIE:
#  设置Cookie默认时长为30分钟
  VALIDITY: 1800